package modules

import "github.com/ditsara/yboard/internal/types"

// ThaiModule is the Thai Kedmanee keyboard layout.
var ThaiModule = types.LanguageModule{
	ID: "thai", Name: "Thai (Kedmanee)", Enabled: true,
	PhoneticMap: map[string][]string{
		"s":  {"ส", "ษ", "ศ", "ซ"},
		"t":  {"ต", "ถ", "ท", "ธ", "ฑ", "ฒ", "ฏ", "ฐ"},
		"k":  {"ก", "ข", "ค", "ฆ", "ฃ", "ฅ"},
		"p":  {"ป", "ผ", "พ", "ภ", "ฝ", "ฟ"},
		"b":  {"บ"},
		"d":  {"ด", "ฎ"},
		"f":  {"ฝ", "ฟ"},
		"r":  {"ร"},
		"l":  {"ล", "ฬ"},
		"w":  {"ว"},
		"y":  {"ย", "ญ"},
		"ch": {"จ", "ฉ", "ช", "ฌ"},
		"ng": {"ง"},
		"m":  {"ม"},
		"n":  {"น", "ณ"},
		"h":  {"ห", "ฮ"},
		"a":  {"ะ", "า", "ำ", "แ", "โ", "ใ", "ไ"},
		"ae": {"แ"},
		"ai": {"ใ", "ไ"},
		"e":  {"เ"},
		"i":  {"ิ", "ี", "ึ", "ื"},
		"o":  {"โ", "อ"},
		"u":  {"ุ", "ู"},
		"ue": {"ึ", "ื"},
		"um": {"ำ"},
	},
	KeyboardRows: [][]types.VisualKey{
		// Number row: backtick through - remapped; = not used in Kedmanee
		{
			{Key: "`", Normal: "_", Shift: "%"},
			{Key: "1", Normal: "ๅ", Shift: "+"},
			{Key: "2", Normal: "/", Shift: "๑"},
			{Key: "3", Normal: "_", Shift: "๒"},
			{Key: "4", Normal: "ภ", Shift: "๓"},
			{Key: "5", Normal: "ถ", Shift: "๔"},
			{Key: "6", Normal: "ุ", Shift: "ู"},
			{Key: "7", Normal: "ึ", Shift: "฿"},
			{Key: "8", Normal: "ค", Shift: "๕"},
			{Key: "9", Normal: "ต", Shift: "๖"},
			{Key: "0", Normal: "จ", Shift: "๗"},
			{Key: "-", Normal: "ข", Shift: "๘"},
			{Key: "=", Normal: "ช", Shift: "๙"},
		},
		// QWERTY row: all 13 positions remapped
		{
			{Key: "q", Normal: "ๆ", Shift: "๐"},
			{Key: "w", Normal: "ไ", Shift: "\""},
			{Key: "e", Normal: "ำ", Shift: "ฎ"},
			{Key: "r", Normal: "พ", Shift: "ฑ"},
			{Key: "t", Normal: "ะ", Shift: "ธ"},
			{Key: "y", Normal: "ั", Shift: "ํ"},
			{Key: "u", Normal: "ี", Shift: "๊"},
			{Key: "i", Normal: "ร", Shift: "ณ"},
			{Key: "o", Normal: "น", Shift: "ฯ"},
			{Key: "p", Normal: "ย", Shift: "ญ"},
			{Key: "[", Normal: "บ", Shift: "ฐ"},
			{Key: "]", Normal: "ล", Shift: ","},
			{Key: `\`, Normal: "ฃ", Shift: "ฅ"},
		},
		// Home row: all 11 positions remapped
		{
			{Key: "a", Normal: "ฟ", Shift: "ฤ"},
			{Key: "s", Normal: "ห", Shift: "ฆ"},
			{Key: "d", Normal: "ก", Shift: "ฏ"},
			{Key: "f", Normal: "ด", Shift: "โ"},
			{Key: "g", Normal: "เ", Shift: "ฌ"},
			{Key: "h", Normal: "้", Shift: "็"},
			{Key: "j", Normal: "่", Shift: "๋"},
			{Key: "k", Normal: "า", Shift: "ษ"},
			{Key: "l", Normal: "ส", Shift: "ศ"},
			{Key: ";", Normal: "ว", Shift: "ซ"},
			{Key: "'", Normal: "ง", Shift: "."},
		},
		// Bottom row: all 10 positions remapped
		{
			{Key: "z", Normal: "ผ", Shift: "("},
			{Key: "x", Normal: "ป", Shift: ")"},
			{Key: "c", Normal: "แ", Shift: "ฉ"},
			{Key: "v", Normal: "อ", Shift: "ฮ"},
			{Key: "b", Normal: "ิ", Shift: "ฺ"},
			{Key: "n", Normal: "ื", Shift: "์"},
			{Key: "m", Normal: "ท", Shift: "?"},
			{Key: ",", Normal: "ม", Shift: "ฒ"},
			{Key: ".", Normal: "ใ", Shift: "ฬ"},
			{Key: "/", Normal: "ฝ", Shift: "ฦ"},
		},
	},
}
